### PR TITLE
Add extend method to assert

### PR DESCRIPTION
**Pull request by franciscocardoso**

### CODE REVIEW

**Comment by ruimarinho** [comment]
Any chance of taking a look at this and other PRs @guillaumepotier :)?

**Comment by guillaumepotier** [comment]
Indeed, great PR, thx!

Could you maybe add a line in documentation for that?

Thx

**Comment by franciscocardoso** [comment]
@guillaumepotier documentation updated.

**Comment by guillaumepotier** [comment]
Good for me.

Thanks!

**Pull request merged**
