### PR TITLE
Fix deepRequired when a Collection has one Assert

### PR DESCRIPTION
**Pull request by promag**

### CODE REVIEW

**Comment by promag** [comment]
@guillaumepotier Missed a test for `Collections` with one `Assert` in #40 which caused an exception when trying to set `deepRequired` on a non `Constraint` constraint.

**Comment by guillaumepotier** [comment]
Ok thanks.

**Comment by promag** [comment]
@guillaumepotier Will you tag this?

**Comment by guillaumepotier** [comment]
@promag absolutely! Done ;)

**Pull request merged**
