### PR TITLE
Add NotEqualTo assert

### PR DESCRIPTION
**Pull request by nunofgs**

### CODE REVIEW

**Comment by ruimarinho** [comment]
Any chance of looking at this PR @guillaumepotier? Thanks!

**Comment by ruimarinho** [comment]
@guillaumepotier is it possible to merge this PR and release a new version?

**Comment by fixe** [comment]
ping @guillaumepotier

**Comment by guillaumepotier** [comment]
Yes,

Sorry guys for doing it so late :(

Packaging a new version right now.

Thanks a lot

Best

**Pull request merged**
