### PR TITLE
Add validation messages

### PR DESCRIPTION
**Pull request by nicolasazrak**
Solves [Issue #44](https://github.com/guillaumepotier/validator.js/issues/44)

Now you can 

```javascript
var  rules = {
  name: [ new Validator.Assert().Length( { min: 10 }, 'Please complete the name with more than 10 characters' ) ],
  email: [ new Validator.Assert().NotBlank('This email is invalid') ],
  lastname: [new Assert().IsString('The lastname must be a valid string')]
};

var model = {
  name: 'Mike',
  lastname: 'Perez'
};

var constraint = new Constraint(rules)
constraint.check(model).messages
constraint.getErrorMessages(validations)
```

and get: 

```javascript
{
  name: ['Please complete the name with more than 10 characters'],
  email: ['This email is invalid']
}
```

I didn't update the documentation but all assertions now have message as the last argument. This solves my problem but I don't know if it covers all posible cases.

### CODE REVIEW

**Comment by nicolasazrak** [comment]
Sorry there are a few test failing and the documentation is outdated. I will be fixing that in the next days, are you interested in this feature?

**Comment by guillaumepotier** [comment]
Could you please squash your commits into one? Diff is really hard to read with two previous obsolete commits. Thank you

**Comment by guillaumepotier** [comment]
Oh and careful with CS, I use:

```javascript
if ( value ) {
for ( value ) { 
while ( value ) { 
```

it seems it lacks some spaces after your `if` and `for` statements :)

**Comment by guillaumepotier** [comment]
Oh, and last and not least, it seems there are no tests for the i18n method right?

**Comment by auro1** [comment]
Status on this one? :-)

**Comment by nicolasazrak** [comment]
@auro1 I wasn't with much time at that time and couldn't think a great solution. I'm closing the pull request and maybe re implement this later.

**Pull request closed without merging**
